insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (101, 'SNAP', 'Approved', 1500, '2022-01-01', '2022-12-31', null);
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (102, 'SNAP', 'Approved', 1500, '2021-01-01', '2021-12-31', null); 
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (103, 'SNAP', 'Denied', null, null, null,'High Income');  
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (104, 'SNAP', 'Denied', null, null, null, 'High Tax');  
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (105, 'CCAP', 'Approved', 1600, '2021-01-01', '2022-12-31', null);
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (106, 'CCAP', 'Approved', 1500, '2020-01-01', '2021-12-31', null); 
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (107, 'CCAP', 'Denied', null, null, null,'Over Returns');  
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (108, 'CCAP', 'Denied', null, null, null,'Not Eligible');
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (109, 'Medicaid', 'Approved', 1400, '2022-01-01', '2022-12-31', null);
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (110, 'Medicaid', 'Approved', 1200, '2021-01-01', '2021-12-31', null); 
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (111, 'Medicaid', 'Denied', null, null, null,'High Income');  
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (112, 'Medicaid', 'Denied', null, null, null, 'High Tax');
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (113, 'Medicare', 'Approved', 1600, '2020-01-01', '2021-12-31', null);
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (114, 'Medicare', 'Approved', 1500, '2022-01-01', '2022-12-31', null); 
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (115, 'Medicare', 'Denied', null, null, null,'High Annual Income');  
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (116, 'Medicare', 'Denied', null, null, null, 'Not Eligible');   
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (117, 'QHP', 'Approved', 1500, '2020-01-01', '2021-12-31', null);
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (118, 'QHP', 'Approved', 1500, '2022-01-01', '2022-12-31', null); 
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (119, 'QHP', 'Denied', null, null, null,'High Annual Income');  
insert into ELIGIBILITY_DTLS(PLAN_ID, PLAN_NAME, PLAN_STATUS, BENEFIT_AMT, START_DATE, END_DATE, DENIAL_REASN) values
  (120, 'QHP', 'Denied', null, null, null, 'Not Eligible');   